//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License Version 2.0 January 2004
//
// https://www.apache.org/licenses/LICENSE-2.0
//
//----------------------------------------

package winapi

const (
	winAPI_CreateRectRgn = iota
	winAPI_SetRectRgn
	winAPI_DeleteObject
	winAPI_CombineRgn
	winAPI_SetDraggableRegions
	winAPI_PtInRegion
	winAPI_ScreenToClient
	winAPI_ClientToScreen
	winAPI_DefWindowProc
	winAPI_DefSubclassProc
	winAPI_CreateRoundRectRgn
	winAPI_SetWindowRgn
	winAPI_SetCursor
	winAPI_LoadCursor
	winAPI_OnPaint
	winAPI_EndPaint
	winAPI_BeginPaint
	winAPI_Arc
	winAPI_AngleChord
	winAPI_CallNextHookEx
	winAPI_CallWindowProc
	winAPI_BitBlt
	winAPI_CreateBitmap
	winAPI_CreateBrushIndirect
	winAPI_CreateBrushWithRadialGradient
	winAPI_CreateCaret
	winAPI_CreateCompatibleBitmap
	winAPI_CreateCompatibleDC
	winAPI_CreateDIBitmap
	winAPI_CreateDIBSection
	winAPI_CreateEllipticRgn
	winAPI_CreateFontIndirect
	winAPI_CreateFontIndirectEx
	winAPI_CreateIconIndirect
	winAPI_CreatePalette
	winAPI_CreatePatternBrush
	winAPI_CreatePenIndirect
	winAPI_CreatePolygonRgn
	winAPI_DeleteCriticalSection
	winAPI_DeleteDC
	winAPI_DestroyCaret
	winAPI_DestroyCursor
	winAPI_DestroyIcon
	winAPI_DrawFrameControl
	winAPI_DrawFocusRect
	winAPI_DrawEdge
	winAPI_DrawText
	winAPI_EnableScrollBar
	winAPI_EnableWindow
	winAPI_EnterCriticalSection
	winAPI_Ellipse
	winAPI_EqualRgn
	winAPI_ExcludeClipRect
	winAPI_ExtCreatePen
	winAPI_ExtTextOut
	winAPI_ExtSelectClipRGN
	winAPI_FillRect
	winAPI_FillRgn
	winAPI_FloodFill
	winAPI_FrameRect
	winAPI_GetActiveWindow
	winAPI_GetBitmapBits
	winAPI_GetBkColor
	winAPI_GetCapture
	winAPI_GetCaretPos
	winAPI_GetClientRect
	winAPI_GetClipBox
	winAPI_GetClipRGN
	winAPI_GetCurrentObject
	winAPI_GetCursorPos
	winAPI_GetDC
	winAPI_GetDeviceCaps
	winAPI_GetDIBits
	winAPI_GetDoubleClickTime
	winAPI_GetFocus
	winAPI_GetFontLanguageInfo
	winAPI_GetForegroundWindow
	winAPI_GetIconInfo
	winAPI_GetKeyState
	winAPI_GetMapMode
	winAPI_GetMonitorInfo
	winAPI_GetDpiForMonitor
	winAPI_GetObject
	winAPI_GetParent
	winAPI_GetProp
	winAPI_GetRgnBox
	winAPI_GetROP2
	winAPI_GetScrollInfo
	winAPI_GetStockObject
	winAPI_GetSysColor
	winAPI_GetSysColorBrush
	winAPI_GetSystemMetrics
	winAPI_GetTextColor
	winAPI_GetTextExtentExPoint
	winAPI_GetTextExtentPoint
	winAPI_GetTextExtentPoint32
	winAPI_GetTextMetrics
	winAPI_GetViewPortExtEx
	winAPI_GetViewPortOrgEx
	winAPI_GetWindowExtEx
	winAPI_GetWindowLong
	winAPI_GetWindowRect
	winAPI_GetWindowSize
	winAPI_GetWindowOrgEx
	winAPI_GradientFill
	winAPI_HideCaret
	winAPI_InitializeCriticalSection
	winAPI_IntersectClipRect
	winAPI_InvalidateRect
	winAPI_InvalidateRgn
	winAPI_IsDBCSLeadByte
	winAPI_IsIconic
	winAPI_IsWindow
	winAPI_IsWindowEnabled
	winAPI_IsWindowVisible
	winAPI_IsZoomed
	winAPI_LeaveCriticalSection
	winAPI_LineTo
	winAPI_LoadBitmap
	winAPI_LoadIcon
	winAPI_MaskBltRop
	winAPI_MaskBlt
	winAPI_MessageBox
	winAPI_MonitorFromPoint
	winAPI_MonitorFromRect
	winAPI_MonitorFromWindow
	winAPI_MoveToEx
	winAPI_OffsetRgn
	winAPI_PaintRgn
	winAPI_Pie
	winAPI_PolyBezier
	winAPI_Polygon
	winAPI_Polyline
	winAPI_PostMessage
	winAPI_RealizePalette
	winAPI_Rectangle
	winAPI_RectInRegion
	winAPI_RectVisible
	winAPI_RedrawWindow
	winAPI_ReleaseCapture
	winAPI_ReleaseDC
	winAPI_RemoveProp
	winAPI_RestoreDC
	winAPI_RoundRect
	winAPI_SaveDC
	winAPI_ScrollWindowEx
	winAPI_SelectClipRGN
	winAPI_SelectObject
	winAPI_SelectPalette
	winAPI_SendMessage
	winAPI_SetActiveWindow
	winAPI_SetBkColor
	winAPI_SetBkMode
	winAPI_SetCapture
	winAPI_SetCaretPos
	winAPI_SetCaretPosEx
	winAPI_SetCursorPos
	winAPI_SetFocus
	winAPI_SetForegroundWindow
	winAPI_SetMapMode
	winAPI_SetMenu
	winAPI_SetParent
	winAPI_SetProp
	winAPI_SetROP2
	winAPI_SetScrollInfo
	winAPI_SetStretchBltMode
	winAPI_SetTextCharacterExtra
	winAPI_SetTextColor
	winAPI_SetWindowLong
	winAPI_SetViewPortExtEx
	winAPI_SetViewPortOrgEx
	winAPI_SetWindowExtEx
	winAPI_SetWindowOrgEx
	winAPI_SetWindowPos
	winAPI_ShowCaret
	winAPI_ShowScrollBar
	winAPI_ShowWindow
	winAPI_StretchBlt
	winAPI_StretchDIBits
	winAPI_SystemParametersInfo
	winAPI_TextOut
	winAPI_UpdateWindow
	winAPI_WindowFromPoint
	winAPI_GetWindowLongPtr
	winAPI_SetWindowLongPtr
	winAPI_GetClassLongPtr
	winAPI_SetClassLongPtr
	winAPI_FindWindow
	winAPI_FindWindowEx
	winAPI_SetWindowText
	winAPI_GetWindowText
	winAPI_GetWindowTextLength
) //end
