//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package lcl

import "github.com/energye/lcl/types"

type TAcceptDateEvent func(sender IObject, date *types.TDateTime, acceptDate *bool)
type TAcceptFileNameEvent func(sender IObject, value *string)
type TAcceptTimeEvent func(sender IObject, time *types.TDateTime, acceptTime *bool)
type TActionEvent func(action IBasicAction, handled *bool)
type TAddHeaderPopupItemEvent func(sender IBaseVirtualTree, column int32, cmd *types.TAddPopupItemType)
type TAlignInsertBeforeEvent func(sender IWinControl, control1 IControl, control2 IControl) bool
type TAlignPositionEvent func(sender IWinControl, control IControl, newLeft *int32, newTop *int32, newWidth *int32, newHeight *int32, alignRect *types.TRect, alignInfo TAlignInfo)
type TBandDragEvent func(sender IObject, control IControl, drag *bool)
type TBandInfoEvent func(sender IObject, control IControl, insets *types.TRect, preferredSize *int32, rowCount *int32)
type TBandMoveEvent func(sender IObject, control IControl, rect *types.TRect)
type TBandPaintEvent func(sender IObject, control IControl, canvas ICanvas, rect *types.TRect, options *types.TBandPaintOptions)
type TCanOffsetEvent func(sender IObject, newOffset *int32, accept *bool)
type TCanResizeEvent func(sender IObject, newSize *int32, accept *bool)
type TCellProcessEvent func(sender IObject, col int32, row int32, processType types.TCellProcessType, value *string)
type TCheckGroupClicked func(sender IObject, index int32)
type TCheckItemChange func(sender IObject, index int32)
type TCheckItemEvent func(item IObject) bool
type TClipboardRequestEvent func(requestedFormatID types.TClipboardFormat, data IStream)
type TCloseEvent func(sender IObject, closeAction *types.TCloseAction)
type TCloseQueryEvent func(sender IObject, canClose *bool)
type TColumnChangeEvent func(sender IBaseVirtualTree, column int32, visible bool)
type TConstrainedResizeEvent func(sender IObject, minWidth *types.TConstraintSize, minHeight *types.TConstraintSize, maxWidth *types.TConstraintSize, maxHeight *types.TConstraintSize)
type TContextPopupEvent func(sender IObject, mousePos types.TPoint, handled *bool)
type TControlShowHintEvent func(sender IObject, hintInfo THintInfo)
type TCustomDateEvent func(sender IObject, date *string)
type TCustomGraphicNotify func()
type TCustomHCCreateSectionClassEvent func(sender ICustomHeaderControl, sectionClass *types.THeaderSectionClass)
type TCustomImageListGetWidthForPPI func(sender ICustomImageList, imageWidth int32, pPI int32, resultWidth *int32)
type TCustomSectionNotifyEvent func(headerControl ICustomHeaderControl, section IHeaderSection)
type TCustomSectionTrackEvent func(headerControl ICustomHeaderControl, section IHeaderSection, width int32, state types.TSectionTrackState)
type TCustomTimeEvent func(sender IObject, time *types.TDateTime)
type TDateRangeCheckEvent func(sender IObject, date *types.TDateTime)
type TDesignerGetShiftStateEvent func() types.TShiftState
type TDesignerIsDesignMsgEvent func(sender IControl, message *types.TLMessage) bool
type TDesignerModifiedEvent func()
type TDesignerNotificationEvent func(component IComponent, operation types.TOperation)
type TDesignerPaintGridEvent func()
type TDesignerPrepareFreeDesignerEvent func(freeComponent bool)
type TDesignerSelectOnlyThisComponentEvent func(component IComponent)
type TDesignerUTF8KeyPressEvent func(uTF8Key *string)
type TDesignerUniqueNameEvent func(baseName string) string
type TDesignerValidateRenameEvent func(component IComponent, curName string, newName string)
type TDestroyResolutionHandleEvent func(sender ICustomImageList, width int32, referenceHandle types.TLCLHandle)
type TDialogResultEvent func(sender IObject, success bool)
type TDockDropEvent func(sender IObject, source IDragDockObject, X int32, Y int32)
type TDockOverEvent func(sender IObject, source IDragDockObject, X int32, Y int32, state types.TDragState, accept *bool)
type TDragDropEvent func(sender IObject, source IObject, X int32, Y int32)
type TDragOverEvent func(sender IObject, source IObject, X int32, Y int32, state types.TDragState, accept *bool)
type TDrawItemEvent func(control IWinControl, index int32, rect types.TRect, state types.TOwnerDrawState)
type TDrawPanelEvent func(statusBar IStatusBar, panel IStatusPanel, rect types.TRect)
type TDropFilesEvent func(sender IObject, fileNames IStringArray)
type TEndDragEvent func(sender IObject, target IObject, X int32, Y int32)
type TFPCanvasCombineColors func(color1 TFPColor, color2 TFPColor) TFPColor
type TFPImgProgressEvent func(sender IObject, stage types.TFPImgProgressStage, percentDone byte, redrawNow bool, R types.TRect, msg string, continue_ *bool)
type TFilterItemEvent func(itemData uintptr, outDone *bool) bool
type TFilterItemExEvent func(caption string, itemData uintptr, outDone *bool) bool
type TFilterNodeEvent func(itemNode ITreeNode, outDone *bool) bool
type TGetCellHintEvent func(sender IObject, col int32, row int32, hintText *string)
type TGetCheckboxStateEvent func(sender IObject, col int32, row int32, value *types.TCheckBoxState)
type TGetColorsEvent func(sender ICustomColorBox, items IStrings)
type TGetDockCaptionEvent func(sender IObject, control IControl, caption *string)
type TGetEditEvent func(sender IObject, col int32, row int32, value *string)
type TGetHandleEvent func(handle *types.HWND)
type TGetPickListEvent func(sender IObject, keyName string, values IStrings)
type TGetSiteInfoEvent func(sender IObject, dockClient IControl, influenceRect *types.TRect, mousePos types.TPoint, canDock *bool)
type THdrEvent func(sender IObject, isColumn bool, index int32)
type THeaderSizingEvent func(sender IObject, isColumn bool, index int32, size int32)
type THelpEvent func(command uint16, data uintptr, callHelp *bool) bool
type THintEvent func(hintStr *string, canShow *bool)
type TIdleEvent func(sender IObject, done *bool)
type TImageIndexEvent func(str string, data IObject, isEnabled *bool) int32
type TImagePaintBackgroundEvent func(sender IObject, canvas ICanvas, rect types.TRect)
type TKeyEvent func(sender IObject, key *uint16, shift types.TShiftState)
type TKeyPressEvent func(sender IObject, key *uint16)
type TLBGetColorsEvent func(sender ICustomColorListBox, items IStrings)
type TLVAdvancedCustomDrawEvent func(sender ICustomListView, rect types.TRect, stage types.TCustomDrawStage, defaultDraw *bool)
type TLVAdvancedCustomDrawItemEvent func(sender ICustomListView, item IListItem, state types.TCustomDrawState, stage types.TCustomDrawStage, defaultDraw *bool)
type TLVAdvancedCustomDrawSubItemEvent func(sender ICustomListView, item IListItem, subItem int32, state types.TCustomDrawState, stage types.TCustomDrawStage, defaultDraw *bool)
type TLVChangeEvent func(sender IObject, item IListItem, change types.TItemChange)
type TLVChangingEvent func(sender IObject, item IListItem, change types.TItemChange, allowChange *bool)
type TLVCheckedItemEvent func(sender IObject, item IListItem)
type TLVColumnClickEvent func(sender IObject, column IListColumn)
type TLVCompareEvent func(sender IObject, item1 IListItem, item2 IListItem, data int32, compare *int32)
type TLVCreateItemClassEvent func(sender ICustomListView, itemClass *types.TListItemClass)
type TLVCustomDrawEvent func(sender ICustomListView, rect types.TRect, defaultDraw *bool)
type TLVCustomDrawItemEvent func(sender ICustomListView, item IListItem, state types.TCustomDrawState, defaultDraw *bool)
type TLVCustomDrawSubItemEvent func(sender ICustomListView, item IListItem, subItem int32, state types.TCustomDrawState, defaultDraw *bool)
type TLVDataEvent func(sender IObject, item IListItem)
type TLVDataFindEvent func(sender IObject, find types.TItemFind, findString string, findPosition types.TPoint, findData uintptr, startIndex int32, direction types.TSearchDirection, wrap bool, index *int32)
type TLVDataHintEvent func(sender IObject, startIndex int32, endIndex int32)
type TLVDataStateChangeEvent func(sender IObject, startIndex int32, endIndex int32, oldState types.TListItemStates, newState types.TListItemStates)
type TLVDeletedEvent func(sender IObject, item IListItem)
type TLVDrawItemEvent func(sender ICustomListView, item IListItem, rect types.TRect, state types.TOwnerDrawState)
type TLVEditedEvent func(sender IObject, item IListItem, value *string)
type TLVEditingEvent func(sender IObject, item IListItem, allowEdit *bool)
type TLVInsertEvent func(sender IObject, item IListItem)
type TLVSelectItemEvent func(sender IObject, item IListItem, selected bool)
type TLinkActionEvent func(sender IObject, linkAction types.TLinkAction, info TLinkMouseInfo, linkStart int32, linkLen int32)
type TListCompareEvent func(list IListControlItems, item1 IListControlItem, item2 IListControlItem) int32
type TMeasureItemEvent func(control IWinControl, index int32, height *int32)
type TMenuChangeEvent func(sender IObject, source IMenuItem, rebuild bool)
type TMenuDrawItemEvent func(sender IObject, canvas ICanvas, rect types.TRect, state types.TOwnerDrawState)
type TMenuMeasureItemEvent func(sender IObject, canvas ICanvas, width *int32, height *int32)
type TModalDialogFinished func(sender IObject, result int32)
type TMouseEvent func(sender IObject, button types.TMouseButton, shift types.TShiftState, X int32, Y int32)
type TMouseMoveEvent func(sender IObject, shift types.TShiftState, X int32, Y int32)
type TMouseWheelEvent func(sender IObject, shift types.TShiftState, wheelDelta int32, mousePos types.TPoint, handled *bool)
type TMouseWheelUpDownEvent func(sender IObject, shift types.TShiftState, mousePos types.TPoint, handled *bool)
type TNotebookTabDragDropEvent func(sender IObject, source IObject, oldIndex int32, newIndex int32, copyDrag bool, done *bool)
type TNotebookTabDragOverEvent func(sender IObject, source IObject, oldIndex int32, newIndex int32, copyDrag bool, accept *bool)
type TNotifyEvent func(sender IObject)
type TOnCompareCells func(sender IObject, col int32, row int32, bCol int32, bRow int32, result *int32)
type TOnDrawCell func(sender IObject, col int32, row int32, rect types.TRect, state types.TGridDrawState)
type TOnPrepareCanvasEvent func(sender IObject, col int32, row int32, state types.TGridDrawState)
type TOnSelectCellEvent func(sender IObject, col int32, row int32, canSelect *bool)
type TOnSelectEvent func(sender IObject, col int32, row int32)
type TOnUserInputEvent func(sender IObject, msg uint32)
type TOnValidateEvent func(sender IObject, col int32, row int32, keyName string, keyValue string)
type TOpenGlCtrlMakeCurrentEvent func(sender IObject, allow *bool)
type TPrintActionEvent func(sender IObject, printAction types.TPrintAction, printCanvas ICanvas, currentPage int32, abortPrint *bool)
type TProgressEvent func(sender IObject, stage types.TFPImgProgressStage, percentDone byte, redrawNow bool, R types.TRect, msg string, continue_ *bool)
type TQueryEndSessionEvent func(cancel *bool)
type TSBCreatePanelClassEvent func(sender IStatusBar, panelClass *types.TStatusPanelClass)
type TScrollEvent func(sender IObject, scrollCode types.TScrollCode, scrollPos *int32)
type TSectionDragEvent func(sender IObject, fromSection IHeaderSection, toSection IHeaderSection, allowDrag *bool)
type TSelectEditorEvent func(sender IObject, col int32, row int32, editor *IWinControl)
type TSelectionChangeEvent func(sender IObject, user bool)
type TSetCheckboxStateEvent func(sender IObject, col int32, row int32, value types.TCheckBoxState)
type TSetEditEvent func(sender IObject, col int32, row int32, value string)
type TShapePointsEvent func(sender IObject, points *IPointArrayWrap, winding *bool)
type TShortcutEvent func(msg *types.TLMKey, handled *bool)
type TShowHintEvent func(hintStr *string, canShow *bool, hintInfo *THintInfo)
type TStartDockEvent func(sender IObject, dragObject *IDragDockObject)
type TStartDragEvent func(sender IObject, dragObject *IDragObject)
type TSysLinkEvent func(sender IObject, link string, linkType types.TSysLinkType)
type TTVAdvancedCustomDrawEvent func(sender ICustomTreeView, rect types.TRect, stage types.TCustomDrawStage, defaultDraw *bool)
type TTVAdvancedCustomDrawItemEvent func(sender ICustomTreeView, node ITreeNode, state types.TCustomDrawState, stage types.TCustomDrawStage, paintImages *bool, defaultDraw *bool)
type TTVChangedEvent func(sender IObject, node ITreeNode)
type TTVChangingEvent func(sender IObject, node ITreeNode, allowChange *bool)
type TTVCollapsingEvent func(sender IObject, node ITreeNode, allowCollapse *bool)
type TTVCompareEvent func(sender IObject, node1 ITreeNode, node2 ITreeNode, compare *int32)
type TTVCreateNodeClassEvent func(sender ICustomTreeView, nodeClass *types.TTreeNodeClass)
type TTVCustomCreateNodeEvent func(sender ICustomTreeView, treeNode *ITreeNode)
type TTVCustomDrawArrowEvent func(sender ICustomTreeView, rect types.TRect, collapsed bool)
type TTVCustomDrawEvent func(sender ICustomTreeView, rect types.TRect, defaultDraw *bool)
type TTVCustomDrawItemEvent func(sender ICustomTreeView, node ITreeNode, state types.TCustomDrawState, defaultDraw *bool)
type TTVEditedEvent func(sender IObject, node ITreeNode, S *string)
type TTVEditingEndEvent func(sender IObject, node ITreeNode, cancel bool)
type TTVEditingEvent func(sender IObject, node ITreeNode, allowEdit *bool)
type TTVExpandedEvent func(sender IObject, node ITreeNode)
type TTVExpandingEvent func(sender IObject, node ITreeNode, allowExpansion *bool)
type TTVHasChildrenEvent func(sender ICustomTreeView, node ITreeNode) bool
type TTVNodeChangedEvent func(sender IObject, node ITreeNode, changeReason types.TTreeNodeChangeReason)
type TTabChangingEvent func(sender IObject, allowChange *bool)
type TTabGetImageEvent func(sender IObject, tabIndex int32, imageIndex *int32)
type TTaskDlgClickEvent func(sender IObject, modalResult types.TModalResult, canClose *bool)
type TTaskDlgTimerEvent func(sender IObject, tickCount uint32, reset *bool)
type TToggledCheckboxEvent func(sender IObject, col int32, row int32, state types.TCheckBoxState)
type TToolBarOnPaintButton func(sender IToolButton, state int32)
type TUDChangingEvent func(sender IObject, allowChange *bool)
type TUDChangingEventEx func(sender IObject, allowChange *bool, newValue types.SmallInt, direction types.TUpDownDirection)
type TUDClickEvent func(sender IObject, button types.TUDBtnType)
type TUTF8KeyPressEvent func(sender IObject, uTF8Key *string)
type TUnDockEvent func(sender IObject, client IControl, newTarget IWinControl, allow *bool)
type TUserCheckBoxImageEvent func(sender IObject, col int32, row int32, checkedState types.TCheckBoxState, imageList *ICustomImageList, imageIndex *int32)
type TUserCheckboxBitmapEvent func(sender IObject, col int32, row int32, checkedState types.TCheckBoxState, bitmap *IBitmap)
type TVSTGetTextEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, textType types.TVSTTextType, cellText *string)
type TVSTNewTextEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, newText string)
type TVSTShortenStringEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, column int32, S string, textSpace int32, result *string, done *bool)
type TVTAddToSelectionEvent func(sender IBaseVirtualTree, node types.PVirtualNode)
type TVTAdvancedHeaderPaintEvent func(sender IVTHeader, paintInfo *THeaderPaintInfo, elements types.THeaderPaintElements)
type TVTAfterAutoFitColumnEvent func(sender IVTHeader, column int32)
type TVTAfterAutoFitColumnsEvent func(sender IVTHeader)
type TVTAfterCellPaintEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, column int32, cellRect types.TRect)
type TVTAfterColumnWidthTrackingEvent func(sender IVTHeader, column int32)
type TVTAfterGetMaxColumnWidthEvent func(sender IVTHeader, column int32, maxWidth *int32)
type TVTAfterHeaderHeightTrackingEvent func(sender IVTHeader)
type TVTAfterItemEraseEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, itemRect types.TRect)
type TVTAfterItemPaintEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, itemRect types.TRect)
type TVTBackgroundPaintEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, R types.TRect, handled *bool)
type TVTBeforeAutoFitColumnEvent func(sender IVTHeader, column int32, smartAutoFitType *types.TSmartAutoFitType, allowed *bool)
type TVTBeforeAutoFitColumnsEvent func(sender IVTHeader, smartAutoFitType *types.TSmartAutoFitType)
type TVTBeforeCellPaintEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, column int32, cellPaintMode types.TVTCellPaintMode, cellRect types.TRect, contentRect *types.TRect)
type TVTBeforeColumnWidthTrackingEvent func(sender IVTHeader, column int32, shift types.TShiftState)
type TVTBeforeDrawLineImageEvent func(sender IBaseVirtualTree, node types.PVirtualNode, level int32, posX *int32)
type TVTBeforeGetMaxColumnWidthEvent func(sender IVTHeader, column int32, useSmartColumnWidth *bool)
type TVTBeforeHeaderHeightTrackingEvent func(sender IVTHeader, shift types.TShiftState)
type TVTBeforeItemEraseEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, itemRect types.TRect, itemColor *types.TColor, eraseAction *types.TItemEraseAction)
type TVTBeforeItemPaintEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, itemRect types.TRect, customDraw *bool)
type TVTBeginCancelEndEditEvent func() bool
type TVTCanSplitterResizeColumnEvent func(sender IVTHeader, P types.TPoint, column int32, allowed *bool)
type TVTCanSplitterResizeHeaderEvent func(sender IVTHeader, P types.TPoint, allowed *bool)
type TVTCanSplitterResizeNodeEvent func(sender IBaseVirtualTree, P types.TPoint, node types.PVirtualNode, column int32, allowed *bool)
type TVTChangeEvent func(sender IBaseVirtualTree, node types.PVirtualNode)
type TVTChangingEvent func(sender IBaseVirtualTree, node types.PVirtualNode, allowed *bool)
type TVTCheckChangingEvent func(sender IBaseVirtualTree, node types.PVirtualNode, newState *types.TCheckState, allowed *bool)
type TVTColumnClickEvent func(sender IBaseVirtualTree, column int32, shift types.TShiftState)
type TVTColumnDblClickEvent func(sender IBaseVirtualTree, column int32, shift types.TShiftState)
type TVTColumnExportEvent func(sender IBaseVirtualTree, exportType types.TVTExportType, column IVirtualTreeColumn)
type TVTColumnWidthDblClickResizeEvent func(sender IVTHeader, column int32, shift types.TShiftState, P types.TPoint, allowed *bool)
type TVTColumnWidthTrackingEvent func(sender IVTHeader, column int32, shift types.TShiftState, trackPoint *types.TPoint, P types.TPoint, allowed *bool)
type TVTCompareEvent func(sender IBaseVirtualTree, node1 types.PVirtualNode, node2 types.PVirtualNode, column int32, result *int32)
type TVTCreateDataObjectEvent func(sender IBaseVirtualTree, outIDataObject *IDataObject)
type TVTCreateDragManagerEvent func(sender IBaseVirtualTree, outDragManager *IVTDragManager)
type TVTCreateEditorEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, outEditLink *IVTEditLink)
type TVTDragAllowedEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, allowed *bool)
type TVTDragDropEvent func(sender IBaseVirtualTree, source IObject, dataObject IDataObject, formats IFormatArray, shift types.TShiftState, pt types.TPoint, effect *uint32, mode types.TDropMode)
type TVTDragOverEvent func(sender IBaseVirtualTree, source IObject, shift types.TShiftState, state types.TDragState, pt types.TPoint, mode types.TDropMode, effect *uint32, accept *bool)
type TVTDrawHintEvent func(sender IBaseVirtualTree, hintCanvas ICanvas, node types.PVirtualNode, R types.TRect, column int32)
type TVTDrawNodeEvent func(sender IBaseVirtualTree, paintInfo TVTPaintInfo)
type TVTDrawTextEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, column int32, cellText string, cellRect types.TRect, defaultDraw *bool)
type TVTEditCancelEvent func(sender IBaseVirtualTree, column int32)
type TVTEditChangeEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32)
type TVTEditChangingEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, allowed *bool)
type TVTFocusChangeEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32)
type TVTFocusChangingEvent func(sender IBaseVirtualTree, oldNode types.PVirtualNode, newNode types.PVirtualNode, oldColumn int32, newColumn int32, allowed *bool)
type TVTFreeNodeEvent func(sender IBaseVirtualTree, node types.PVirtualNode)
type TVTGetBoundsEvent func() types.TRect
type TVTGetCellIsEmptyEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, isEmpty *bool)
type TVTGetCursorEvent func(sender IBaseVirtualTree, cursor *types.TCursor)
type TVTGetHeaderCursorEvent func(sender IVTHeader, cursor *types.HCURSOR)
type TVTGetHintEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, lineBreakStyle *types.TVTTooltipLineBreakStyle, hintText *string)
type TVTGetHintSizeEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, R *types.TRect)
type TVTGetImageEvent func(sender IBaseVirtualTree, node types.PVirtualNode, kind types.TVTImageKind, column int32, ghosted *bool, imageIndex *int32)
type TVTGetImageExEvent func(sender IBaseVirtualTree, node types.PVirtualNode, kind types.TVTImageKind, column int32, ghosted *bool, imageIndex *int32, imageList *ICustomImageList)
type TVTGetImageTextEvent func(sender IBaseVirtualTree, node types.PVirtualNode, kind types.TVTImageKind, column int32, imageText *string)
type TVTGetLineStyleEvent func(sender IBaseVirtualTree, bits *uintptr)
type TVTGetNodeDataSizeEvent func(sender IBaseVirtualTree, nodeDataSize *int32)
type TVTGetNodeWidthEvent func(sender IBaseVirtualTree, hintCanvas ICanvas, node types.PVirtualNode, column int32, nodeWidth *int32)
type TVTGetUserClipboardFormatsEvent func(sender IBaseVirtualTree, formats *IFormatEtcArrayWrap)
type TVTHeaderClickEvent func(sender IVTHeader, hitInfo TVTHeaderHitInfo)
type TVTHeaderDraggedEvent func(sender IVTHeader, column int32, oldPosition int32)
type TVTHeaderDraggedOutEvent func(sender IVTHeader, column int32, dropPosition types.TPoint)
type TVTHeaderDraggingEvent func(sender IVTHeader, column int32, allowed *bool)
type TVTHeaderHeightDblClickResizeEvent func(sender IVTHeader, P *types.TPoint, shift types.TShiftState, allowed *bool)
type TVTHeaderHeightTrackingEvent func(sender IVTHeader, P *types.TPoint, shift types.TShiftState, allowed *bool)
type TVTHeaderMouseEvent func(sender IVTHeader, button types.TMouseButton, shift types.TShiftState, X int32, Y int32)
type TVTHeaderMouseMoveEvent func(sender IVTHeader, shift types.TShiftState, X int32, Y int32)
type TVTHeaderNotifyEvent func(sender IVTHeader, column int32)
type TVTHeaderPaintEvent func(sender IVTHeader, headerCanvas ICanvas, column IVirtualTreeColumn, R types.TRect, hover bool, pressed bool, dropMark types.TVTDropMarkMode)
type TVTHeaderPaintQueryElementsEvent func(sender IVTHeader, paintInfo *THeaderPaintInfo, elements *types.THeaderPaintElements)
type TVTHelpContextEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, helpContext *int32)
type TVTHintKindEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, kind *types.TVTHintKind)
type TVTHotNodeChangeEvent func(sender IBaseVirtualTree, oldNode types.PVirtualNode, newNode types.PVirtualNode)
type TVTIncrementalSearchEvent func(sender IBaseVirtualTree, node types.PVirtualNode, searchText string, result *int32)
type TVTInitChildrenEvent func(sender IBaseVirtualTree, node types.PVirtualNode, childCount *uint32)
type TVTInitNodeEvent func(sender IBaseVirtualTree, parentNode types.PVirtualNode, node types.PVirtualNode, initialStates *types.TVirtualNodeInitStates)
type TVTKeyActionEvent func(sender IBaseVirtualTree, charCode *uint16, shift *types.TShiftState, doDefault *bool)
type TVTMeasureItemEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, nodeHeight *int32)
type TVTMeasureTextEvent func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, column int32, cellText string, extent *int32)
type TVTNodeClickEvent func(sender IBaseVirtualTree, hitInfo THitInfo)
type TVTNodeCopiedEvent func(sender IBaseVirtualTree, node types.PVirtualNode)
type TVTNodeCopyingEvent func(sender IBaseVirtualTree, node types.PVirtualNode, target types.PVirtualNode, allowed *bool)
type TVTNodeExportEvent func(sender IBaseVirtualTree, exportType types.TVTExportType, node types.PVirtualNode) bool
type TVTNodeHeightDblClickResizeEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, shift types.TShiftState, P types.TPoint, allowed *bool)
type TVTNodeHeightTrackingEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, shift types.TShiftState, trackPoint *types.TPoint, P types.TPoint, allowed *bool)
type TVTNodeMovedEvent func(sender IBaseVirtualTree, node types.PVirtualNode)
type TVTNodeMovingEvent func(sender IBaseVirtualTree, node types.PVirtualNode, target types.PVirtualNode, allowed *bool)
type TVTOperationEvent func(sender IBaseVirtualTree, operationKind types.TVTOperationKind)
type TVTPaintEvent func(sender IBaseVirtualTree, targetCanvas ICanvas)
type TVTPaintText func(sender IBaseVirtualTree, targetCanvas ICanvas, node types.PVirtualNode, column int32, textType types.TVSTTextType)
type TVTPopupEvent func(sender IBaseVirtualTree, node types.PVirtualNode, column int32, P types.TPoint, askParent *bool, popupMenu *IPopupMenu)
type TVTPrepareEditEvent func(tree IBaseVirtualTree, node types.PVirtualNode, column int32) bool
type TVTProcessMessageEvent func(msg *types.TLMessage)
type TVTRemoveFromSelectionEvent func(sender IBaseVirtualTree, node types.PVirtualNode)
type TVTSaveNodeEvent func(sender IBaseVirtualTree, node types.PVirtualNode, stream IStream)
type TVTSaveTreeEvent func(sender IBaseVirtualTree, stream IStream)
type TVTScrollBarShowEvent func(sender IBaseVirtualTree, bar int32, show bool)
type TVTScrollEvent func(sender IBaseVirtualTree, deltaX int32, deltaY int32)
type TVTSetBoundsEvent func(R types.TRect)
type TVTStateChangeEvent func(sender IBaseVirtualTree, enter types.TVirtualTreeStates, leave types.TVirtualTreeStates)
type TVTStructureChangeEvent func(sender IBaseVirtualTree, node types.PVirtualNode, reason types.TChangeReason)
type TVTTreeExportEvent func(sender IBaseVirtualTree, exportType types.TVTExportType)
type TVTUpdatingEvent func(sender IBaseVirtualTree, state types.TVTUpdateState)
type TValidateEntryEvent func(sender IObject, col int32, row int32, oldValue string, newValue *string)
type TWndMethod func(theMessage *types.TLMessage)
