//----------------------------------------
// The code is automatically generated by the generate-tool.
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package lcl

import (
	. "github.com/energye/lcl/api"
	"github.com/energye/lcl/api/imports"
)

// IUnknown 底层接口
type IUnknown interface {
	AddRef(instance uintptr) bool
	Release(instance uintptr) bool
}

type Unknown uintptr

func (Unknown) AddRef(instance uintptr) bool {
	if instance != 0 {
		r1 := unknownImportAPI().SysCallN(0, instance)
		return GoBool(r1)
	}
	return false
}

func (Unknown) Release(instance uintptr) bool {
	if instance != 0 {
		r1 := unknownImportAPI().SysCallN(1, instance)
		if GoBool(r1) {
			return true
		}
	}
	return false
}

var (
	unknownImport       *imports.Imports = nil
	unknownImportTables                  = []*imports.Table{
		/*0*/ imports.NewTable("COMUnknown_AddRef", 0),
		/*1*/ imports.NewTable("COMUnknown_Release", 0),
	}
)

func unknownImportAPI() *imports.Imports {
	if unknownImport == nil {
		unknownImport = NewDefaultImports()
		unknownImport.SetImportTable(unknownImportTables)
		unknownImportTables = nil
	}
	return unknownImport
}
