//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package internal

import "github.com/energye/lcl/api/imports"

// api import index table
var wkAutoGenImports = []*imports.Table{
	/*0*/ imports.NewTable("WkContextMenuItem_Create", 0),
	/*1*/ imports.NewTable("WkContextMenuItem_Data", 0),
	/*2*/ imports.NewTable("WkContextMenuItem_GetAction", 0),
	/*3*/ imports.NewTable("WkContextMenuItem_GetStockAction", 0),
	/*4*/ imports.NewTable("WkContextMenuItem_GetSubmenu", 0),
	/*5*/ imports.NewTable("WkContextMenuItem_IsSeparator", 0),
	/*6*/ imports.NewTable("WkContextMenuItem_NewFromAction", 0),
	/*7*/ imports.NewTable("WkContextMenuItem_NewFromStockAction", 0),
	/*8*/ imports.NewTable("WkContextMenuItem_NewFromStockActionWithLabel", 0),
	/*9*/ imports.NewTable("WkContextMenuItem_NewSeparator", 0),
	/*10*/ imports.NewTable("WkContextMenuItem_NewWithSubmenu", 0),
	/*11*/ imports.NewTable("WkContextMenuItem_SetSubmenu", 0),
	/*12*/ imports.NewTable("WkContextMenu_Append", 0),
	/*13*/ imports.NewTable("WkContextMenu_Create", 0),
	/*14*/ imports.NewTable("WkContextMenu_Create1", 0),
	/*15*/ imports.NewTable("WkContextMenu_Data", 0),
	/*16*/ imports.NewTable("WkContextMenu_GetItemAtPosition", 0),
	/*17*/ imports.NewTable("WkContextMenu_GetItemsLength", 0),
	/*18*/ imports.NewTable("WkContextMenu_Insert", 0),
	/*19*/ imports.NewTable("WkContextMenu_Prepend", 0),
	/*20*/ imports.NewTable("WkContextMenu_Remove", 0),
	/*21*/ imports.NewTable("WkContextMenu_RemoveAll", 0),
	/*22*/ imports.NewTable("WkCookieDate_Create", 0),
	/*23*/ imports.NewTable("WkCookieDate_Day", 0),
	/*24*/ imports.NewTable("WkCookieDate_Hour", 0),
	/*25*/ imports.NewTable("WkCookieDate_Minute", 0),
	/*26*/ imports.NewTable("WkCookieDate_Month", 0),
	/*27*/ imports.NewTable("WkCookieDate_NewCookieDate", 0),
	/*28*/ imports.NewTable("WkCookieDate_NewCustomCookieDate", 0),
	/*29*/ imports.NewTable("WkCookieDate_Offset", 0),
	/*30*/ imports.NewTable("WkCookieDate_Second", 0),
	/*31*/ imports.NewTable("WkCookieDate_ToLongTime", 0),
	/*32*/ imports.NewTable("WkCookieDate_ToStringTime", 0),
	/*33*/ imports.NewTable("WkCookieDate_Utc", 0),
	/*34*/ imports.NewTable("WkCookieDate_Year", 0),
	/*35*/ imports.NewTable("WkCookieList_Create", 0),
	/*36*/ imports.NewTable("WkCookieList_GetCookie", 0),
	/*37*/ imports.NewTable("WkCookieList_Length", 0),
	/*38*/ imports.NewTable("WkCookieManager_AddCookie", 0),
	/*39*/ imports.NewTable("WkCookieManager_Create", 0),
	/*40*/ imports.NewTable("WkCookieManager_Create1", 0),
	/*41*/ imports.NewTable("WkCookieManager_DeleteAllCookies", 0),
	/*42*/ imports.NewTable("WkCookieManager_DeleteCookie", 0),
	/*43*/ imports.NewTable("WkCookieManager_DeleteCookiesForDomain", 0),
	/*44*/ imports.NewTable("WkCookieManager_GetAcceptPolicy", 0),
	/*45*/ imports.NewTable("WkCookieManager_GetCookies", 0),
	/*46*/ imports.NewTable("WkCookieManager_SetAcceptPolicy", 0),
	/*47*/ imports.NewTable("WkCookieManager_SetPersistentStorage", 0),
	/*48*/ imports.NewTable("WkCookie_Create", 0),
	/*49*/ imports.NewTable("WkCookie_Data", 0),
	/*50*/ imports.NewTable("WkCookie_Domain", 0),
	/*51*/ imports.NewTable("WkCookie_Expires", 0),
	/*52*/ imports.NewTable("WkCookie_HttpOnly", 0),
	/*53*/ imports.NewTable("WkCookie_Name", 0),
	/*54*/ imports.NewTable("WkCookie_NewCookie", 0),
	/*55*/ imports.NewTable("WkCookie_Path", 0),
	/*56*/ imports.NewTable("WkCookie_Secure", 0),
	/*57*/ imports.NewTable("WkCookie_SetMaxAge", 0),
	/*58*/ imports.NewTable("WkCookie_Value", 0),
	/*59*/ imports.NewTable("WkHeaders_Append", 0),
	/*60*/ imports.NewTable("WkHeaders_Clear", 0),
	/*61*/ imports.NewTable("WkHeaders_Create", 0),
	/*62*/ imports.NewTable("WkHeaders_Create1", 0),
	/*63*/ imports.NewTable("WkHeaders_List", 0),
	/*64*/ imports.NewTable("WkHeaders_Remove", 0),
	/*65*/ imports.NewTable("WkHeaders_Replace", 0),
	/*66*/ imports.NewTable("WkInputStream_Close", 0),
	/*67*/ imports.NewTable("WkInputStream_Create", 0),
	/*68*/ imports.NewTable("WkInputStream_Create1", 0),
	/*69*/ imports.NewTable("WkInputStream_Data", 0),
	/*70*/ imports.NewTable("WkInputStream_Read", 0),
	/*71*/ imports.NewTable("WkJSValue_BooleanValue", 0),
	/*72*/ imports.NewTable("WkJSValue_Create", 0),
	/*73*/ imports.NewTable("WkJSValue_Create1", 0),
	/*74*/ imports.NewTable("WkJSValue_ExceptionMessage", 0),
	/*75*/ imports.NewTable("WkJSValue_IntegerValue", 0),
	/*76*/ imports.NewTable("WkJSValue_NumberValue", 0),
	/*77*/ imports.NewTable("WkJSValue_StringValue", 0),
	/*78*/ imports.NewTable("WkJSValue_ValueType", 0),
	/*79*/ imports.NewTable("WkNavigationAction_Create", 0),
	/*80*/ imports.NewTable("WkNavigationAction_GetRequest", 0),
	/*81*/ imports.NewTable("WkPolicyDecision_Create", 0),
	/*82*/ imports.NewTable("WkPolicyDecision_Data", 0),
	/*83*/ imports.NewTable("WkPolicyDecision_Download", 0),
	/*84*/ imports.NewTable("WkPolicyDecision_Ignore", 0),
	/*85*/ imports.NewTable("WkPolicyDecision_Use", 0),
	/*86*/ imports.NewTable("WkPolicyDecision_UseWithPolicies", 0),
	/*87*/ imports.NewTable("WkSettings_AutoLoadImages", 0),
	/*88*/ imports.NewTable("WkSettings_Create", 0),
	/*89*/ imports.NewTable("WkSettings_Create1", 0),
	/*90*/ imports.NewTable("WkSettings_Data", 0),
	/*91*/ imports.NewTable("WkSettings_EnableDeveloperExtras", 0),
	/*92*/ imports.NewTable("WkSettings_EnableJavascript", 0),
	/*93*/ imports.NewTable("WkSettings_SetHardwareAccelerationPolicy", 0),
	/*94*/ imports.NewTable("WkSettings_SetUserAgentWithApplicationDetails", 0),
	/*95*/ imports.NewTable("WkURIRequest_Create", 0),
	/*96*/ imports.NewTable("WkURIRequest_Headers", 0),
	/*97*/ imports.NewTable("WkURIRequest_Method", 0),
	/*98*/ imports.NewTable("WkURIRequest_NewURIRequest", 0),
	/*99*/ imports.NewTable("WkURIRequest_URI", 0),
	/*100*/ imports.NewTable("WkURIResponse_Create", 0),
	/*101*/ imports.NewTable("WkURIResponse_GetContentLength", 0),
	/*102*/ imports.NewTable("WkURIResponse_GetMimeType", 0),
	/*103*/ imports.NewTable("WkURIResponse_GetStatusCode", 0),
	/*104*/ imports.NewTable("WkURIResponse_GetSuggestedFilename", 0),
	/*105*/ imports.NewTable("WkURIResponse_Headers", 0),
	/*106*/ imports.NewTable("WkURIResponse_URI", 0),
	/*107*/ imports.NewTable("WkURISchemeRequest_Body", 0),
	/*108*/ imports.NewTable("WkURISchemeRequest_Create", 0),
	/*109*/ imports.NewTable("WkURISchemeRequest_Data", 0),
	/*110*/ imports.NewTable("WkURISchemeRequest_Finish", 0),
	/*111*/ imports.NewTable("WkURISchemeRequest_FinishError", 0),
	/*112*/ imports.NewTable("WkURISchemeRequest_FinishWithResponse", 0),
	/*113*/ imports.NewTable("WkURISchemeRequest_Headers", 0),
	/*114*/ imports.NewTable("WkURISchemeRequest_Method", 0),
	/*115*/ imports.NewTable("WkURISchemeRequest_Path", 0),
	/*116*/ imports.NewTable("WkURISchemeRequest_Scheme", 0),
	/*117*/ imports.NewTable("WkURISchemeRequest_Uri", 0),
	/*118*/ imports.NewTable("WkURISchemeRequest_WebView", 0),
	/*119*/ imports.NewTable("WkWebContext_Create", 0),
	/*120*/ imports.NewTable("WkWebContext_Default", 0),
	/*121*/ imports.NewTable("WkWebContext_DownloadURI", 0),
	/*122*/ imports.NewTable("WkWebContext_GetCookieManager", 0),
	/*123*/ imports.NewTable("WkWebContext_New", 0),
	/*124*/ imports.NewTable("WkWebContext_RegisterURIScheme", 0),
	/*125*/ imports.NewTable("WkWebContext_SetCacheModel", 0),
	/*126*/ imports.NewTable("WkWebContext_SetWetPreferredLanguages", 0),
	/*127*/ imports.NewTable("WkWebViewParent_Create", 0),
	/*128*/ imports.NewTable("WkWebViewParent_FreeChild", 0),
	/*129*/ imports.NewTable("WkWebViewParent_ScrolledWindow", 0),
	/*130*/ imports.NewTable("WkWebViewParent_WebView", 0),
	/*131*/ imports.NewTable("WkWebsitePolicies_Create", 0),
	/*132*/ imports.NewTable("WkWebsitePolicies_Create1", 0),
	/*133*/ imports.NewTable("WkWebsitePolicies_Data", 0),
	/*134*/ imports.NewTable("WkWebsitePolicies_GetAutoplayPolicy", 0),
	/*135*/ imports.NewTable("WkWebview_CanGoBack", 0),
	/*136*/ imports.NewTable("WkWebview_CanGoForward", 0),
	/*137*/ imports.NewTable("WkWebview_CookieManager", 0),
	/*138*/ imports.NewTable("WkWebview_Create", 0),
	/*139*/ imports.NewTable("WkWebview_CreateBrowser", 0),
	/*140*/ imports.NewTable("WkWebview_EnabledDevtools", 0),
	/*141*/ imports.NewTable("WkWebview_ExecuteScript", 0),
	/*142*/ imports.NewTable("WkWebview_FreeWebview", 0),
	/*143*/ imports.NewTable("WkWebview_GetSettings", 0),
	/*144*/ imports.NewTable("WkWebview_GetTitle", 0),
	/*145*/ imports.NewTable("WkWebview_GoBack", 0),
	/*146*/ imports.NewTable("WkWebview_GoForward", 0),
	/*147*/ imports.NewTable("WkWebview_IsLoading", 0),
	/*148*/ imports.NewTable("WkWebview_LoadHTML", 0),
	/*149*/ imports.NewTable("WkWebview_LoadURL", 0),
	/*150*/ imports.NewTable("WkWebview_RegisterScriptCode", 0),
	/*151*/ imports.NewTable("WkWebview_RegisterScriptMessageHandler", 0),
	/*152*/ imports.NewTable("WkWebview_Reload", 0),
	/*153*/ imports.NewTable("WkWebview_SetOnAddCookieFinish", 0),
	/*154*/ imports.NewTable("WkWebview_SetOnContextMenu", 0),
	/*155*/ imports.NewTable("WkWebview_SetOnContextMenuCommand", 0),
	/*156*/ imports.NewTable("WkWebview_SetOnContextMenuDismissed", 0),
	/*157*/ imports.NewTable("WkWebview_SetOnDecidePolicy", 0),
	/*158*/ imports.NewTable("WkWebview_SetOnDeleteCookieFinish", 0),
	/*159*/ imports.NewTable("WkWebview_SetOnExecuteScriptFinished", 0),
	/*160*/ imports.NewTable("WkWebview_SetOnGetAcceptPolicyFinish", 0),
	/*161*/ imports.NewTable("WkWebview_SetOnGetCookiesFinish", 0),
	/*162*/ imports.NewTable("WkWebview_SetOnLoadChange", 0),
	/*163*/ imports.NewTable("WkWebview_SetOnLoadFailed", 0),
	/*164*/ imports.NewTable("WkWebview_SetOnMousePress", 0),
	/*165*/ imports.NewTable("WkWebview_SetOnMouseRelease", 0),
	/*166*/ imports.NewTable("WkWebview_SetOnProcessMessage", 0),
	/*167*/ imports.NewTable("WkWebview_SetOnURISchemeRequest", 0),
	/*168*/ imports.NewTable("WkWebview_SetOnWebProcessTerminated", 0),
	/*169*/ imports.NewTable("WkWebview_SetSettings", 0),
	/*170*/ imports.NewTable("WkWebview_ShowDevtools", 0),
	/*171*/ imports.NewTable("WkWebview_StartDrag", 0),
	/*172*/ imports.NewTable("WkWebview_Stop", 0),
	/*173*/ imports.NewTable("WkWebview_TerminateWebProcess", 0),
	/*174*/ imports.NewTable("WkWebview_TryClose", 0),
	/*175*/ imports.NewTable("WkWebview_WebView", 0),
}

// InitWKAutoGenImport 自动生成导出表
func InitWKAutoGenImport(imp *imports.Imports) {
	imp.SetOk(true)
	imp.SetImportTable(wkAutoGenImports)
}
